### PR TITLE
Added Tek MDO3024, 4 Series and 5 Series as compatible

### PR DESCRIPTION
**Pull request by htro**
Tested 3 Tektronix oscilloscopes. LXI discover and SCPI ok.

### CODE REVIEW

**Comment by lundmar** [comment]
Great, thanks!

Do you know if the instruments actually supports retrieving the display data via SCPI commands?

If so, we can fix or add a plugin to support them.

**Comment by htro** [comment]
Sorry, I haven't looked into that.

**Comment by lundmar** [comment]
That's fine. I'll look into it when I get time. Perhaps I can ask for your help testing once I've added screenshot support for these instruments? :)

**Comment by htro** [comment]
Yes I have access to those scopes at work and I can test the screenshot functionality if you implement it.

**Comment by lundmar** [comment]
Thanks. I'll get back to you once I have something to test.

**Pull request merged**
